//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProje {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Example {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Example() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcProje.Example", typeof(Example).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ağır Devir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ağır_Devir {
            get {
                return ResourceManager.GetString("Ağır_Devir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AĞIR TONAJ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ağır_tonaj {
            get {
                return ResourceManager.GetString("Ağır_tonaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ANASAYFA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARKA DİNGİL GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Arka_Dingil {
            get {
                return ResourceManager.GetString("Arka_Dingil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Askerlik Durumunuz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Askerlik_Durumunuz {
            get {
                return ResourceManager.GetString("Askerlik Durumunuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BAĞLANTI GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Baglantı {
            get {
                return ResourceManager.GetString("Baglantı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışmak İstediğiniz Alan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Çalışmak_İstediğiniz_Alan {
            get {
                return ResourceManager.GetString("Çalışmak İstediğiniz Alan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇEKİ ÜRÜNLERİ GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ceki_urunleri {
            get {
                return ResourceManager.GetString("Ceki_urunleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cinsiyet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Cinsiyet {
            get {
                return ResourceManager.GetString("Cinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DEBRİYAJ GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Debriyaj {
            get {
                return ResourceManager.GetString("Debriyaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Devamını Oku benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Devam {
            get {
                return ResourceManager.GetString("Devam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DİFERANSİYEL GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Diferansiyel {
            get {
                return ResourceManager.GetString("Diferansiyel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DİREKSİYON GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Direksiyon {
            get {
                return ResourceManager.GetString("Direksiyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dogum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Dogum {
            get {
                return ResourceManager.GetString("Dogum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dogum Yeri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Dogum_Yeri {
            get {
                return ResourceManager.GetString("Dogum_Yeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FREN GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Fren {
            get {
                return ResourceManager.GetString("Fren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HAKKIMIZDA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merhaba Dünya benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HİDROLİK GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hidrolik {
            get {
                return ResourceManager.GetString("Hidrolik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İLETİŞİM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string İletişim {
            get {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaldırma Kapasitesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Kaldırma_Kapasitesi {
            get {
                return ResourceManager.GetString("Kaldırma_Kapasitesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KAPORTA GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Kaporta {
            get {
                return ResourceManager.GetString("Kaporta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KARİYER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Kariyer {
            get {
                return ResourceManager.GetString("Kariyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KATEGORİLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Kategoriler {
            get {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KİNG PİNLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string King_pinler {
            get {
                return ResourceManager.GetString("King_pinler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KONTEYNER KİLİTLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Konteyner__kilidleri {
            get {
                return ResourceManager.GetString("Konteyner_ kilidleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Konu {
            get {
                return ResourceManager.GetString("Konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maaş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Maaş {
            get {
                return ResourceManager.GetString("Maaş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maksimum Kol Gücü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Maksimum_Kol_Gücü {
            get {
                return ResourceManager.GetString("Maksimum_Kol_Gücü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medeni Durumunuzu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Medeni_Durumunuzu {
            get {
                return ResourceManager.GetString("Medeni Durumunuzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meslek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Meslek {
            get {
                return ResourceManager.GetString("Meslek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOTOR GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Okul benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Okul {
            get {
                return ResourceManager.GetString("Okul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÖN DİNGİL GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ön_dingil {
            get {
                return ResourceManager.GetString("Ön_dingil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÖN DİNGİL GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ön_Dingil_grubu {
            get {
                return ResourceManager.GetString("Ön_Dingil_grubu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PARK AYAKLARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PARK_AYAKLARI {
            get {
                return ResourceManager.GetString("PARK AYAKLARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refanslarımız ve İş Ortaklarımız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Refanslar {
            get {
                return ResourceManager.GetString("Refanslar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RÖMORK KRİKOLARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Römok_krikoları {
            get {
                return ResourceManager.GetString("Römok_krikoları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ŞANZIMAN GRUBU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Şanzıman {
            get {
                return ResourceManager.GetString("Şanzıman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seçili Dil Bulunmuyor, default dil görüntüleniyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectedLanguage {
            get {
                return ResourceManager.GetString("SelectedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seri Devir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Seri_Devir {
            get {
                return ResourceManager.GetString("Seri_Devir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERTİFİKALAR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Sertifikalar {
            get {
                return ResourceManager.GetString("Sertifikalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sipariş Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Siparis_Kodu {
            get {
                return ResourceManager.GetString("Siparis_Kodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sipariş Kodu Örneği benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Sipariş_Kodu_Örneği {
            get {
                return ResourceManager.GetString("Sipariş Kodu Örneği", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Eklenen Ürünler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Son_eklenen {
            get {
                return ResourceManager.GetString("Son_eklenen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Soyadı {
            get {
                return ResourceManager.GetString("Soyadı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulunamıyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tanim {
            get {
                return ResourceManager.GetString("Tanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şirketleri, sektördeki lider konumunu yenilikçi yaklaşımıyla sağlamış bir kuruluş olarak bilinmektedir. Müşteri odaklı hizmet anlayışı ve kalite standartlarındaki sürekli yükseliş, şirketini rakiplerinden ayıran önemli özelliklerden biridir. Aynı zamanda iş hayatına değer katan bir kurum olarak, çalışan memnuniyetini ve takım ruhunu ön planda tutmaktadır. Etik değerlere olan bağlılığı ve sosyal sorumluluk bilinciyle de toplumsal katkı sağlamayı amaçlamaktadır. Yenilikçi projeler ve stratejilerle sektöründe  [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tanıtım {
            get {
                return ResourceManager.GetString("Tanıtım", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışanlar şirketin başarısına katkıda bulunan en değerli varlıklardan biridir. Uzmanlık alanlarındaki yüksek becerileri ve işbirliği yapma yetenekleriyle öne çıkan ekip üyeleri, iş yerinde olumlu bir atmosfer yaratarak ekip ruhunu güçlendiriyor. Motivasyonu ve çalışma disipliniyle şirket kültürünü şekillendiren çalışanlar her zaman güvenilir ve profesyonel bir şekilde çalışırlar. Ayrıca sürekli gelişime ve öğrenmeye açık tutumlarıyla da dikkat çekiyorlar. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tanıtım1 {
            get {
                return ResourceManager.GetString("Tanıtım1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu şirket, sektördeki lider konumunu yenilikçi yaklaşımıyla sağlamış bir kuruluş olarak tanınıyor. Müşteri odaklı hizmet anlayışı ve sürekli yükselen kalite standartları, onları rakiplerinden ayıran önemli özellikler arasında. Aynı zamanda iş hayatına değer katan bir kurum olarak, çalışan memnuniyetini ve takım ruhunu ön planda tutmaları takdire şayan. Etik değerlere olan bağlılıkları ve toplumsal sorumluluk bilinci, topluma gerçek anlamda katkı sağlamayı hedefliyorlar. Yenilikçi projeler ve stratejilerle s [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tanıtım2 {
            get {
                return ResourceManager.GetString("Tanıtım2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taşıma Kapasitesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Taşıma_Kapasitesi {
            get {
                return ResourceManager.GetString("Taşıma_Kapasitesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAİLER ÜRÜNLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Trailer_Ürünleri {
            get {
                return ResourceManager.GetString("Trailer Ürünleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRAKTÖR ÜRÜNLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Traktör_Ürünleri {
            get {
                return ResourceManager.GetString("Traktör Ürünleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Detaylı Fotografları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ürün_Fotografları {
            get {
                return ResourceManager.GetString("Ürün_Fotografları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ürün_Kodu {
            get {
                return ResourceManager.GetString("Ürün_Kodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜNLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Urunler {
            get {
                return ResourceManager.GetString("Urunler", resourceCulture);
            }
        }
    }
}
